#!/bin/bash
# Cross-compile the demo binary for the BeagleBone in a Docker container.
# A full parallel build takes well under a minute on a desktop, so this is
# the fast path for development; compile.sh on the BeagleBone remains the
# reference build.
#
# The PRU firmware arrays (10.01_base/4_deploy_<suffix>/*_array.c) are
# generated by the TI clpru compiler, which only exists on the BeagleBone.
# This script fetches them from the device when they are missing locally;
# after changing PRU sources, run compile.sh on the device once and delete
# the local copies to re-fetch.
#
# usage:
#   ./crossbuild.sh            build for QBUS (demo binary)
#   ./crossbuild.sh -u         build for UNIBUS
#   ./crossbuild.sh -d         build and deploy the binary to $QUNIBONE_HOST
#   ./crossbuild.sh -c         clean object directory first
#
# environment:
#   QUNIBONE_HOST   ssh destination of the device (default hans@192.168.2.221)
#   QUNIBONE_REMOTE_DIR  QUniBone directory on the device (default ~/QUniBone)

set -e
cd "$(dirname "$0")"

QUNIBONE_HOST=${QUNIBONE_HOST:-hans@192.168.2.221}
QUNIBONE_REMOTE_DIR=${QUNIBONE_REMOTE_DIR:-QUniBone}
IMAGE=qunibone-crossbuild

SUFFIX=_q
PLATFORM=QBUS
DEPLOY=0
CLEAN=0
while getopts "udc" opt; do
    case $opt in
        u) SUFFIX=_u; PLATFORM=UNIBUS;;
        d) DEPLOY=1;;
        c) CLEAN=1;;
        *) exit 1;;
    esac
done

# builder image: Debian with the armhf cross toolchain
if ! docker image inspect $IMAGE >/dev/null 2>&1; then
    echo "Building $IMAGE docker image ..."
    docker build -t $IMAGE - <<'EOF'
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf make file \
        curl ca-certificates bzip2 \
    && rm -rf /var/lib/apt/lists/*
# Sun RPC for the blinkenlight API client: modern glibc no longer bundles it;
# libtirpc replaces it, built without GSSAPI so it links statically
RUN curl -sL https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.4.tar.bz2 | tar xj -C /tmp \
    && cd /tmp/libtirpc-1.3.4 \
    && ./configure --host=arm-linux-gnueabihf --disable-gssapi --disable-shared \
        --prefix=/usr/local/tirpc-armhf \
    && make -j"$(nproc)" && make install \
    && rm -rf /tmp/libtirpc-1.3.4
EOF
fi

# prussdrv headers: installed system-wide on the device; only the prebuilt
# libprussdrv.a is in git
PRUSS_INCLUDE_DIR=91_3rd_party/am335x_pru_package/include
if [ ! -f "$PRUSS_INCLUDE_DIR/prussdrv.h" ]; then
    echo "Fetching prussdrv headers from $QUNIBONE_HOST ..."
    mkdir -p "$PRUSS_INCLUDE_DIR"
    scp "$QUNIBONE_HOST:/usr/include/prussdrv.h" \
        "$QUNIBONE_HOST:/usr/include/pruss_intc_mapping.h" \
        "$PRUSS_INCLUDE_DIR/"
fi

# PRU firmware arrays: clpru output, fetched from the device
PRU_DEPLOY_DIR=10.01_base/4_deploy$SUFFIX
PRU_ARRAYS=$(ls "$PRU_DEPLOY_DIR"/*_array.c 2>/dev/null || true)
if [ -z "$PRU_ARRAYS" ]; then
    echo "Fetching PRU firmware arrays from $QUNIBONE_HOST ..."
    scp "$QUNIBONE_HOST:$QUNIBONE_REMOTE_DIR/$PRU_DEPLOY_DIR/*_array.c" \
        "$PRU_DEPLOY_DIR/"
fi
# make must see them as newer than the PRU sources, or it tries to run clpru
touch "$PRU_DEPLOY_DIR"/*_array.c

OBJDIR="10.03_app_demo/4_deploy$SUFFIX"
HEADER_STAMP="$OBJDIR/.headers.sha"

# Adding or removing a virtual method, or changing a struct layout, in a
# shared header is an ABI change: incremental make relinks stale objects
# compiled against the old layout, and the mismatched vtables crash at
# runtime (a null-vtable jump). The makefile's header dependencies do not
# cover every object, so force a clean build whenever any header under
# 10.01_base/10.02_devices changed since the last build. A content hash is
# used, so re-touching a header without editing it does not trigger a clean.
header_hash() {
    find 10.01_base 10.02_devices -type f \( -name '*.h' -o -name '*.hpp' \) \
        -print0 | sort -z | xargs -0 cat 2>/dev/null | shasum | cut -d' ' -f1
}
HEADER_HASH=$(header_hash)
if [ $CLEAN = 0 ] && [ -f "$HEADER_STAMP" ] \
        && [ "$(cat "$HEADER_STAMP")" != "$HEADER_HASH" ]; then
    echo "Headers under 10.01_base/10.02_devices changed — forcing a clean build (ABI safety)."
    CLEAN=1
fi

if [ $CLEAN = 1 ]; then
    rm -rf "$OBJDIR"
fi

docker run --rm -v "$PWD:/qunibone" -w /qunibone/10.03_app_demo/2_src $IMAGE \
    make -f makefile$SUFFIX -j"$(sysctl -n hw.ncpu 2>/dev/null || echo 4)" \
        QUNIBONE_DIR=/qunibone \
        MAKE_CONFIGURATION=RELEASE \
        MAKE_TARGET_ARCH=BBB \
        BBB_CC=arm-linux-gnueabihf-gcc \
        CCDEFS=-I/usr/local/tirpc-armhf/include/tirpc \
        EXTRA_LIBS="-L/usr/local/tirpc-armhf/lib -ltirpc" \
        all

BINARY=$OBJDIR/demo
file "$BINARY"

# record the header state so the next incremental build detects ABI changes
# (the build recreated $OBJDIR); only reached on a successful build (set -e)
echo "$HEADER_HASH" > "$HEADER_STAMP"

if [ $DEPLOY = 1 ]; then
    echo "Deploying to $QUNIBONE_HOST:$QUNIBONE_REMOTE_DIR/$BINARY ..."
    # upload beside the binary, then rename: replaces it even while it runs
    scp "$BINARY" "$QUNIBONE_HOST:$QUNIBONE_REMOTE_DIR/$BINARY.new"
    ssh "$QUNIBONE_HOST" "mv '$QUNIBONE_REMOTE_DIR/$BINARY.new' '$QUNIBONE_REMOTE_DIR/$BINARY'"
fi
