#!/bin/sh
# Turn a binary file into a C array, so it can be linked into the executable
# rather than shipped beside it.
#
# The PRU firmware is embedded this way twice over: as instruction words for
# the prussdrv backend, which hexpru already produces, and as the ELF file
# itself for remoteproc, which is what this makes.
#
# usage: bin2c.sh <file> <symbol> <output.c>

set -e

in=$1
sym=$2
out=$3

if [ -z "$in" ] || [ -z "$sym" ] || [ -z "$out" ]; then
    echo "usage: $0 <file> <symbol> <output.c>" >&2
    exit 2
fi
[ -r "$in" ] || { echo "$0: cannot read $in" >&2; exit 1; }

size=$(wc -c < "$in" | tr -d ' ')

{
    echo "/* generated by tools/bin2c.sh from $(basename "$in") - do not edit */"
    echo "#include <stdint.h>"
    echo
    echo "const uint8_t ${sym}[] = {"
    # od and awk are everywhere; xxd is not
    od -An -tx1 -v "$in" | awk '
        { for (i = 1; i <= NF; i++) {
              printf "0x%s,", $i
              if (++n % 16 == 0) printf "\n"
          } }
        END { if (n % 16) printf "\n" }'
    echo "};"
    echo "const uint32_t ${sym}_size = ${size};"
} > "$out"
